/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Bruce Wayne
 */
public class prueba extends javax.swing.JDialog {

    /**
     * Creates new form prueba
     */
    public prueba(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    prueba() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cambia = new javax.swing.JLabel();
        imagen = new javax.swing.JPanel();
        linea = new javax.swing.JSeparator();
        ResExacto = new javax.swing.JButton();
        ACampeon = new javax.swing.JButton();
        label_apostar = new javax.swing.JLabel();
        a_partidos = new javax.swing.JLabel();
        a_campeon = new javax.swing.JLabel();
        a_goleador = new javax.swing.JLabel();
        AGoleador = new javax.swing.JButton();
        APartidos = new javax.swing.JButton();
        label_resultado = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        local = new javax.swing.JLabel();
        visitante = new javax.swing.JLabel();
        vs = new javax.swing.JLabel();
        competicion = new javax.swing.JLabel();
        lista_partidos = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cambia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cambia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ResExacto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ResExacto.setText("Ex!");
        ResExacto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ACampeon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ACampeon.setText("C!");
        ACampeon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_apostar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_apostar.setText("Apuestas Ibet");

        a_partidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a_partidos.setText("Partidos");

        a_campeon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a_campeon.setText("Campeon");

        a_goleador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a_goleador.setText("Goleador");

        AGoleador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AGoleador.setText("G!");
        AGoleador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        APartidos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        APartidos.setText("P!");
        APartidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        APartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APartidosActionPerformed(evt);
            }
        });

        label_resultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_resultado.setText("Res. Exacto");

        javax.swing.GroupLayout imagenLayout = new javax.swing.GroupLayout(imagen);
        imagen.setLayout(imagenLayout);
        imagenLayout.setHorizontalGroup(
            imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagenLayout.createSequentialGroup()
                        .addGroup(imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imagenLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(label_apostar))
                            .addGroup(imagenLayout.createSequentialGroup()
                                .addGroup(imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(a_partidos)
                                        .addComponent(ACampeon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(APartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(imagenLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(a_campeon)))
                                .addGap(43, 43, 43)
                                .addGroup(imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResExacto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_resultado)
                                    .addComponent(AGoleador, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a_goleador))))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagenLayout.createSequentialGroup()
                        .addComponent(linea, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        imagenLayout.setVerticalGroup(
            imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_apostar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(APartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResExacto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_partidos)
                    .addComponent(label_resultado))
                .addGap(18, 18, 18)
                .addGroup(imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACampeon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AGoleador, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_campeon)
                    .addComponent(a_goleador))
                .addGap(18, 18, 18)
                .addComponent(linea, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("Fecha");

        local.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        local.setText("Local");

        visitante.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        visitante.setText("Visitante");

        vs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vs.setText("VS");

        competicion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        competicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        competicion.setText("Competicion");

        lista_partidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lista_partidos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manya vs Hijos", "Real Madrid vs Barcelona", "Boca vs River", "Santos vs Sao Paulo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cambia, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(local, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vs)
                        .addGap(35, 35, 35)
                        .addComponent(visitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lista_partidos, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(competicion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cambia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lista_partidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(competicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(local)
                    .addComponent(visitante)
                    .addComponent(vs))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void APartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APartidosActionPerformed
        // TODO add your handling code here:
        label_apostar.setVisible(true);
        label_apostar.setText("Apostar a Partidos");
    }//GEN-LAST:event_APartidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                prueba dialog = new prueba(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACampeon;
    private javax.swing.JButton AGoleador;
    private javax.swing.JButton APartidos;
    private javax.swing.JButton ResExacto;
    private javax.swing.JLabel a_campeon;
    private javax.swing.JLabel a_goleador;
    private javax.swing.JLabel a_partidos;
    private javax.swing.JLabel cambia;
    private javax.swing.JLabel competicion;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel imagen;
    private javax.swing.JLabel label_apostar;
    private javax.swing.JLabel label_resultado;
    private javax.swing.JSeparator linea;
    private javax.swing.JComboBox lista_partidos;
    private javax.swing.JLabel local;
    private javax.swing.JLabel visitante;
    private javax.swing.JLabel vs;
    // End of variables declaration//GEN-END:variables
}
